# Site settings
email: jun@beomi.net
paginate: 5
paginate_path: "/blog/page-:num"
timezone: Asia/Seoul

# SEO settings
title: Beomi's Tech Blog
description: Beomi의 기술 블로그
url: "https://beomi.github.io"
default_img: /img/profile_beomi.jpg

# Profile settings
name: Junbum Lee
profile_img: "/img/profile_beomi.jpg"
profile: "Python으로 백엔드를, JS로 프론트엔드를 다루고 있습니다.<br>패스트캠퍼스에서 실전 웹 크롤링 CAMP를 진행하고 있습니다.<br>공적인 연락은 아래 이메일 주소를 통해주세요!"
social:
  github: "https://github.com/beomi"
  facebook: "https://facebook.com/Junbum.L"

# Build settings
exclude: ["Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
